version: "2.1"
services:
  app:
    build: .
    links:
      - mysql
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpasswd
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
