version: "3.1"
services:
  app:
    build: .
    links:
      - mysql
    ports:
      - "5000:5000"
  mysql:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpasswd
